version: "3.7"
services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./nginx/sf4playground.conf:/etc/nginx/conf.d/sf4playground.conf
  php:
    image: php:7.3-fpm
    volumes:
      - .:/var/www/html