version: "3.7"
services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./nginx/sf4playground.conf:/etc/nginx/conf.d/sf4playground.conf

  phpfpm:
    image: joshrob/php73fpm
    volumes:
      - .:/var/www/html
    environment:
      XDEBUG_CONFIG: remote_host=192.168.0.18