version: "3.7"
services:
  nginx:
    image: nginx:alpine
    volumes:
      - .:/var/www/html
      - ./nginx/sf4playground.conf:/etc/nginx/conf.d/sf4playground.conf
    environment:
      VIRTUAL_HOST: sf4playground.docker

  phpfpm:
    image: joshrob/php73fpm
    volumes:
      - .:/var/www/html
    environment:
      XDEBUG_CONFIG: remote_host=192.168.0.18

  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sf4playground
    volumes:
      - ~/docker_dev_mysql:/var/lib/mysql

  adminer:
    image: adminer
    environment:
      VIRTUAL_HOST: adminer.docker