version: "3.7"
services:
  nginx_test:
    image: nginx:alpine
    volumes:
    - .:/var/www/html
    - ./nginx/sf4playground_test.conf:/etc/nginx/conf.d/sf4playground_test.conf
    environment:
      VIRTUAL_HOST: sf4playground-test.docker
    networks:
    - test_network

  phpfpm_test:
    image: joshrob/php73fpm
    volumes:
    - .:/var/www/html
    environment:
      XDEBUG_CONFIG: remote_host=192.168.0.18
    networks:
    - test_network

  database_test:
    image: mysql:5.7
    environment:
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: test
    volumes:
      - test_data_volume:/var/lib/mysql
    networks:
    - test_network

volumes:
  test_data_volume:

networks:
  test_network: