version: 2
jobs:
  build:
    docker:
      - image: joshrob/circleci-primary:latest
    working_directory: ~/var/www/html
    steps:
      - checkout
      - run: "composer install && php bin/phpunit"