version: 2
jobs:
  build:
    docker:
      - image: joshrob/circleci-primary:latest
        environment:
          APP_ENV: test
          DATABASE_URL: "mysql://test:test@127.0.0.1:3306/test"
      - image: mysql:5.7
        environment:
          MYSQL_USER: test
          MYSQL_PASSWORD: test
          MYSQL_ROOT_PASSWORD: test
          MYSQL_DATABASE: test
    resource_class: small
    working_directory: ~/var/www/html
    environment:
      ROLLBAR_ENVIRONMENT: development
    steps:
      - checkout
      - run:
          name: Wait for the database
          command: dockerize -wait tcp://localhost:3306 -timeout 1m
      - run:
          name: Run unit tests
          command: |
            env
            composer install
            php bin/console doctrine:migrations:migrate --no-interaction -vvv --env=test
            php bin/console doctrine:fixtures:load --no-interaction
            php bin/phpunit