version: 2.1
orbs:
  deploy: rollbar/deploy@1.0.1
jobs:
  build:
    docker:
      - image: joshrob/circleci-primary:latest
    working_directory: ~/var/www/html
    steps:
      - run:
          name: Notify rollbar start
          command: deploy/notify_deploy_started
      - checkout
      - run:
          name: Run unit tests
          command: "composer install && php bin/phpunit"
      - run:
          name: Notify rollbar finish
          command: deploy/notify_deploy_finished
