version: 2.1
orbs:
  deploy: rollbar/deploy@1.0.1
jobs:
  build:
    docker:
      - image: joshrob/circleci-primary:latest
    working_directory: ~/var/www/html
    environment:
      ROLLBAR_ENVIRONMENT: development
    steps:
      - deploy/notify_deploy_started:
          environment: $ROLLBAR_ENVIRONMENT
      - checkout
      - run:
          name: Run unit tests
          command: "composer install && php bin/phpunit"
      - deploy/notify_deploy_finished:
          deploy_id: $ROLLBAR_DEPLOY_ID
          status: succeeded
