version: 2
jobs:
  build:
    docker:
      - image: joshrob/circleci-primary:latest
    working_directory: ~/var/www/html
    steps:
      - checkout
      - run: "composer install && php bin/phpunit"
      - run: curl https://api.rollbar.com/api/1/deploy/ \
          -F access_token='$ROLLBAR_ACCESS_TOKEN' \
          -F environment=production \
          -F revision=$CIRCLE_SHA1 \
          -F rollbar_username=$ROLLBAR_USERNAME \
          -F local_username=$CIRCLE_USERNAME