version: 2.1
orbs:
  deploy: rollbar/deploy@1.0.1
jobs:
  build:
    docker:
      - image: joshrob/circleci-primary:latest
    resource_class: small
    working_directory: ~/var/www/html
    environment:
      ROLLBAR_ENVIRONMENT: development
    steps:
      - deploy/notify_deploy_started:
          environment: ${ROLLBAR_ENVIRONMENT}
      - checkout
      - run:
          name: Run unit tests
          command: "composer install && php bin/phpunit && echo \"export ROLLBAR_STATUS=succeeded\" >> $BASH_ENV"
      - run:
          name: Rollbar - Notify Deploy Succeeded
          command: |
            curl -X PATCH \
            https://api.rollbar.com/api/1/deploy/$ROLLBAR_DEPLOY_ID?access_token=$ROLLBAR_ACCESS_TOKEN \
              --data '{"status":"succeeded"}'
          when: on_success
      - run:
          name: Rollbar - Notify Deploy Failed
          command: |
            curl -X PATCH \
            https://api.rollbar.com/api/1/deploy/$ROLLBAR_DEPLOY_ID?access_token=$ROLLBAR_ACCESS_TOKEN \
              --data '{"status":"failed"}'
          when: on_fail